poudriere_task:
  freebsd_instance:
    image_family: freebsd-14-0-snap
    cpu: 8
    memory: 8G
    nested_virtualization: true

  environment:
    CIRRUS_CLONE_DEPTH: 1

  install_script:
    - pkg install -y git poudriere-devel

  jail_script:
    - poudriere jail -c -j router -v 13.0-RELEASE -K GENERIC

  ports_script:
    - poudriere ports -c -p ports

  build_script:
    - echo 'security/strongswan' > router-pkglist
    - poudriere bulk -j router -p ports -f router-pkglist

  image_script:
    - poudriere image -t firmware -j router -s 4g -p ports -h router -n router -f router-pkglist

  test_script:
    - sh /usr/share/examples/bhyve/vmrun.sh -u -t tap0 -t tap1 -d /usr/local/poudriere/data/images/router.img router
